name: intl_example
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=2.12.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.5
  intl: ^0.18.0
  equatable: ^2.0.5
  flutter_bloc: ^8.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  generate: true
